### ISSUE TITLE
Add WCAG Accessibility Audit Developer UI 

### ISSUE THREAD

**Issue by ctimbi** [josehilera/a11y-evaluation-tools#2]
Here´s a new tool to consider in the list
**WCAG Accessibility Audit Developer UI**
https://chrome.google.com/webstore/detail/wcag-accessibility-audit/kpfleokokmllclahndmochhenmhncoej?hl=es&utm_source=permalink

**Comment by josehilera** [comment]
Thanks Cristian. The tool has been included in the list.
